robot:
  type: piper

teleop:
  type: piper_teleop

dataset:
  repo_id: kai/test
  single_task: Test
  fps: 20
  episode_time_s: 600
  reset_time_s: 15
  num_episodes: 50
  streaming_encoding: true
  encoder_threads: 5
  vcodec: auto
  push_to_hub: false

display_data: false
display_compressed_images: true
